kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-crm-ocp-pruebainterna
  namespace: open-crm-ocp-dev
  labels:
    app: open-crm-ocp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: open-crm-ocp
  template:
    metadata:
      labels:
        app: open-crm-ocp
    spec:
      volumes:
        - name: teco-adam-config
          secret:
            secretName: teco-adam-config
            defaultMode: 420
      containers:
        - resources:
          terminationMessagePath: /dev/termination-log
          name: ubi8
          env:
            - name: http_proxy
              value: 'proxyappl.telecom.arg.telecom.com.ar:8080'
            - name: https_proxy
              value: 'proxyappl.telecom.arg.telecom.com.ar:8080'
            - name: no_proxy
              value: >-
                .apps.ocp4-rh.cloudteco.com.ar,.cloudteco.com.ar,.run.app,.googleapis.com,.telecom.com.ar
            - name: HTTP_PROXY
              value: 'proxyappl.telecom.arg.telecom.com.ar:8080'
            - name: HTTPS_PROXY
              value: 'proxyappl.telecom.arg.telecom.com.ar:8080'
            - name: NO_PROXY
              value: >-
                .apps.ocp4-rh.cloudteco.com.ar,.cloudteco.com.ar,.run.app,.googleapis.com,.telecom.com.ar
            - name: CATALINA_OPTS
              value: >-
                -Dhttp.proxyHost=proxyappl.telecom.arg.telecom.com.ar
                -Dhttp.proxyPort=8080
                -Dhttps.proxyHost=proxyappl.telecom.arg.telecom.com.ar
                -Dhttps.proxyPort=8080          
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: teco-adam-config
              mountPath: /app/config
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/open-crm-ocp-dev/open-crm-ocp-dev-build:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      securityContext: {}
      schedulerName: default-scheduler
      dnsConfig:
        nameservers:
          - 10.244.71.57
          - 10.66.72.20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
